# Auto-Generated by cargo-bitbake 0.3.16-alpha.0
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get peridio-agent could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/peridio-agent/0.1.0"
SRC_URI += "git://git@github.com/peridio/porcini;protocol=ssh;nobranch=1;branch=PRO-61/agent"
SRCREV = "8d042fc32b883a8486138413a814d247b70a1e00"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV_append = ".AUTOINC+8d042fc32b"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://Apache-2.0;md5=generateme \
"

SUMMARY = "Peridio Agent"
HOMEPAGE = "https://peridio.com"
LICENSE = "Apache-2.0"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include peridio-agent-${PV}.inc
include peridio-agent.inc
